# Generated by Django 5.1.1 on 2024-10-05 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='result',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.ImageField(blank=True, default=1, upload_to='icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'heic', 'heif'])]),
            preserve_default=False,
        ),
    ]
